### ISSUE TITLE
Problems with new JNRPE version

### ISSUE THREAD

**Issue by angoca** [ziccardi/jnrpe#21]
My project db2-jnrpe is based on JNRPE and it has a problem while running with the most recent version (2.0.5).

I have a ticket associated with this problem: https://github.com/angoca/db2-jnrpe/issues/15

![erro-db2-jnrpe](https://cloud.githubusercontent.com/assets/15154330/10536879/46a98be8-73e6-11e5-8bac-b0db65501e62.PNG)

The list of plugins are recognized when running interactively; however, when the scripts are called they throw the previous exception.

The problem seems related to public constructors: https://github.com/angoca/db2-jnrpe/blob/master/src/main/java/com/github/angoca/db2jnrpe/plugins/jnrpe/CheckAverageSortingTimePlugin.java#L142

**Comment by ziccardi** [comment]
That's weird. The error happens at this code:
```
pluginInterface = pluginDef.getPluginClass().newInstance();
```
That would means that no public no arg constructor is available...

**Comment by angoca** [comment]
Hi Massimiliano,

Did you change something on the API? the classloaders are still the same?

**Comment by ziccardi** [comment]
New developments moved to version 3.0.0
