### ISSUE TITLE
jnrpe server won't run properly

### ISSUE THREAD

**Issue by auermich93** [ziccardi/jnrpe#24]
Hi guys,
I have some issues with the jnrpe-server-2.0.4.

Whenever I try to run: ./jnrpe -c ../etc/jnrpe.ini on my console,
the command doesn't complete, thus I press Ctrl+C to abort it.
Now looking into the log file (stored in /logs/ folder),  I get following statement:
Listening on SSL/127.0.0.1:6000
Seems like everything would be ok, but however, running netstat -ln, I can't find there any entry about it. Also trying to execute an command via ./(j)check_nrpe doesn't work, neither without SSL (-n). However, my nrpe server on port 3000 is listening and accepting requests.

I have already tested several things, but in the end nothing worked properly. What I have noticed so far, that there are some difficulties with resolving the path to the jnrpe.ini file. Regarding the log file,
two major issues occur:
1) ConfigurationUtils.locate(): base is null, name is jnrpe.ini
2) Javassist unavailable: You don't have Javassist in your class path or you don't have enough permission .....

It seems like, org.apache.commons.utils have some problems to resolve the path to the config file, probably it can't handle properly linux paths. However, jnrpe is loading at the end the default
config file, which is actually the one I am using (regarding logs). Both issues are handled as
DEBUG entries, so this shouldn't be a real problem. You may noticed, that I have changed some
settings on the config file, like port, ssl and so forth, but also the default config didn't succeed. I have also added several allow-address entries to ensure, that my own address won't get denied.

The last approach, that I have tried out, was the usage of a .xml config file, but neither this worked.
The command didn't complete as well. Just another thing to mention, I have added entries
into the hosts.allow file as well as configured iptables/ufw to ensure, that my firewall isn't blocking any request. What is confusing me a bit, that the jnrpe interactive console is working and also accepting commands.

My last try will be to run another version of jnrpe-server. If this won't work neither, I have no further idea. I really beg for help.

Thanks in advance!

PS: I have also tried to run the installer (.jar), no success as well.

**Comment by ziccardi** [comment]
If you want to send jnrpe in background you have to call it as:

`./jnrpe -c ../etc/jnrpe.ini &`

otherwise, it will be in foreground, thus your 'does not complete' issue.
